version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: ovm-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: onlinevoting
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-padmin"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ovm-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onlinevoting?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mysql_data: {}